---
title: "Cancer Incidences in The Borders"
output: html_notebook
---

```{r}
# load packages
library(tidyverse)
library(janitor)
library(leaflet)
library(here)

here
```

```{r}
# load data (7 datasets)
geography_codes <- read_csv(here("data/geography_codes_and_labels_hb2014_01042019.csv")) %>%  clean_names() # HB code and HB name
cancer_network_region_annual_incidence <- read_csv(here("data/annual_cancer_incidence_cancer_network_region.csv"))  %>%  clean_names() # region, cancer type, sex, age counts, crude 
scotland_annual_incidence <- read_csv(here("data/annual_cancer_incidence_scotland.csv"))  %>%  clean_names()
healthboard_incidence <- read_csv(here("data/incidence_by_hb.csv"))  %>%  clean_names()
cancer_network_region_5yr_incidence <- read_csv(here("data/five_yr_summary_incidence_cancer_network_region.csv"))  %>%  clean_names()
hb_5yr_incidence <- read_csv(here("data/five_yr_summary_incidence_hb.csv"))  %>%  clean_names()
scotland_5yr_incidence <- read_csv(here("data/five_yr_summary_incidence_scotland.csv"))  %>%  clean_names()

```

```{r}
hb_5yr_incidence %>% 
  filter(sex == "All") %>% 
  
```

```{r}
healthboard_incidence %>% 
  filter(hb == "S08000016",
         sex == "All") %>% 
  group_by(cancer_site) %>% 
  summarise(count = sum(incidences_all_ages)) %>% 
  arrange(desc(count)) %>% 
  filter(cancer_site != "All cancer types") %>% 
  head(10) %>%  


 ggplot(aes(x = cancer_site, y = count)) +
 geom_col() +
theme(axis.text.x = element_text(angle = 90, vjust = 0))
      
```
```{r}
hb_5yr_incidence %>% 
  filter(hb == "S08000016",
         sex != "All") %>% 
  group_by(cancer_site, sex) %>% 
  summarise(count = sum(incidences_all_ages)) %>% 
  arrange(desc(count)) %>% 
  filter(cancer_site != "All cancer types") %>% 
  head(10) %>%  
  ggplot(aes(x = cancer_site, y = count, fill = sex)) +
  geom_col() +
  coord_flip() +
  labs(x = "Cancer",
       y = "Incidences",
       title = "10 Highest Cancers in NHS Borders (2017 - 2021)") +
  scale_fill_manual(values = c("Females" = "#003087", "Male" = "#00A9CE" ))
  
```

```{r}
# total rate per gender per age
hb_5yr_incidence_longer <- hb_5yr_incidence %>% 
  select(hb, cancer_site, sex, incidence_rate_age_under5:incidence_rate_age85and_over) %>% 
  filter(hb == "S08000016") %>% 
  filter(sex != "All") %>% 
    pivot_longer(cols = incidence_rate_age_under5:incidence_rate_age85and_over,names_to = "age",values_to = "rate") %>% 
  mutate(age = str_remove(string = age, pattern = "incidence_rate_age[_]*"),
         age = str_replace(string = age, pattern = "to", replacement = " - "),
         age = str_replace(string = age, pattern = "under", replacement = "<"),
         age = str_replace(string = age, pattern = "85and_over", replacement = ">85"),
        age = factor(age, levels = c("<5", "5 - 9", "10 - 14", "15 - 19", "20 - 24", "25 - 29", "30 - 34", "35 - 39", "40 - 44", "45 - 49", "50 - 54", "55 - 59", "60 - 64", "65 - 69", "70 - 74", "75 - 79", "80 - 84", ">85"))) %>% 
    group_by(age, sex) %>% 
  summarise(total_rate = sum(rate)) 
```
```{r}
# biggest cancer per gender per age
biggest_cancer_age <- 
hb_5yr_incidence %>% 
  select(hb, cancer_site, sex, incidences_age_under5:incidences_age85and_over) %>% 
  filter(hb == "S08000016") %>% 
   filter(sex != "All") %>% 
    pivot_longer(cols = incidences_age_under5:incidences_age85and_over,names_to = "age",values_to = "rate") %>% 
  mutate(age = str_remove(string = age, pattern = "incidences_age[_]*"),
         age = str_replace(string = age, pattern = "to", replacement = " - "),
         age = str_replace(string = age, pattern = "under", replacement = "<"),
         age = str_replace(string = age, pattern = "85and_over", replacement = ">85")) %>% 
  filter(cancer_site != "All cancer types") %>% 
  group_by(age, sex,cancer_site) %>% 
  summarise(total_incidences = sum(rate)) %>% 
 slice_max(order_by = total_incidences) %>% 
  filter(total_incidences > 1)


```
```{r}
right_join(hb_5yr_incidence_longer, biggest_cancer_age, by ="age") %>% 
  select(- sex.y) %>% 
   mutate(age = factor(age, levels = c("<5", "5 - 9", "10 - 14", "15 - 19", "20 - 24", "25 - 29", "30 - 34", "35 - 39", "40 - 44", "45 - 49", "50 - 54", "55 - 59", "60 - 64", "65 - 69", "70 - 74", "75 - 79", "80 - 84", ">85"))) %>% 
 filter(cancer_site != "Acute lymphoblastic leukaemia") %>% 
  mutate(cancer_site = ifelse(age == "15 - 19", "Skin Cancer (Basal/Melanoma) & Thyroid", cancer_site)) %>% 
  mutate(cancer_site = ifelse(cancer_site == "Carcinoma in situ of the cervix uteri", "Cervical", cancer_site)) %>% 
  mutate(cancer_site = ifelse(cancer_site == "All brain and CNS tumours (malignant and non-malignant)", "Brain/CNS", cancer_site)) %>% 
  filter(!(sex.x == "Females" & cancer_site == "Testis")) %>% 
  filter(!(sex.x == "Male" & cancer_site == "Cervical")) %>% 
  filter(!(sex.x == "Females" & cancer_site == "Prostate")) %>% 
  ggplot(aes(x = age, y = total_rate, fill = cancer_site, group = sex.x)) + 
  geom_col() +
  coord_flip(expand = FALSE) +
  labs(y = "Rate",
       x = "Age") +
  facet_wrap(~sex.x) 
```

```{r}

```

